### ISSUE TITLE
Evaluation shell script not found

### ISSUE THREAD

**Issue by aoxolotl** [neulab/soft-gazetteers#1]
Hey,
When I run the training script I get an error 
```/bin/sh: 1: ./conlleval_f1: not found```
This is the script for calculating the f1 score, I assume. Is this missing from the repo? Or is this script available elsewhere?

**Comment by shrutirij** [comment]
Sorry for the late response. The script is in the repo here: https://github.com/neulab/soft-gazetteers/blob/master/code/conlleval_f1.
